# Validate Yarn constraints on install.
enableConstraintsChecks: true

# Don't send telemetry data to Yarn.
enableTelemetry: false

# Inject .env for all Yarn commands.
injectEnvironmentFiles:
  - ".env?"

# Use Plug'n'Play (no node_modules).
nodeLinker: pnp

# Set up the registry for the appfarm-internal scope.
npmScopes:
  appfarm-internal:
    npmAlwaysAuth: true
    npmRegistryServer: https://europe-west1-npm.pkg.dev/appfarm-internal/appfarm-internal
